apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    db: postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: postgres-storageclass
  hostPath:
    path: /mnt/data/postgres