apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    db: postgres
spec:
  type: ClusterIP
  selector:
    db: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres