apiVersion: v1
kind: Service
metadata:
  name: todo-front-service
  labels:
    app: todo-front
spec:
  type: ClusterIP
  selector:
    app: todo-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80