#! /bin/bash

mkdir foo
cd foo
mkdir dummy empty
touch dummy/file{1..2}.txt
if [ -n "$1" ]; then
    echo "$1" > dummy/file1.txt
else
    echo "Me encanta la bash!!" > dummy/file1.txt
fi
cp dummy/file1.txt dummy/file2.txt
mv dummy/file2.txt empty/file2.txt

