apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      imagePullSecrets:
      - name: myghcr-secret
      containers:
      - name: todo-api
        image: ghcr.io/raullopezpenalva/todo-api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: todo-api-config