apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  labels:
    app: todo-app
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "todos_db"
  DB_VERSION: "10.4"